{{- if and (or (eq .Values.deploymentMode "controller") .Values.controller.enabled) .Values.controller.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kube-node-ready.fullname" . }}-controller
  namespace: {{ .Values.controller.metrics.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "kube-node-ready.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.controller.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.controller.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "kube-node-ready.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  endpoints:
  - port: metrics
    {{- with .Values.controller.metrics.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.controller.metrics.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    path: /metrics
    scheme: http
    {{- with .Values.controller.metrics.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.controller.metrics.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.controller.metrics.serviceMonitor.targetLabels }}
  targetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
