apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-node-ready.fullname" . }}-controller-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-node-ready.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kube-node-ready.fullname" . }}-controller-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-node-ready.controllerServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
