{{- if and (eq .Values.deploymentMode "daemonset") .Values.daemonset.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-node-ready.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-node-ready.labels" . | nindent 4 }}
  {{- with .Values.daemonset.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
