apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-node-ready.fullname" . }}-worker
  labels:
    {{- include "kube-node-ready.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
rules:
# Permissions for service discovery checks (checks kubernetes service and endpoints in default namespace)
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get"]

