# Artifact Hub repository metadata file
# https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml
repositoryID: kube-node-ready
owners:
  - name: imunhatep
    email: 432393+imunhatep@users.noreply.github.com
