apiVersion: v2
name: kube-node-ready
description: A Helm chart for Kubernetes node network verification
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - kubernetes
  - node
  - verification
  - networking
  - karpenter
home: https://github.com/imunhatep/kube-node-ready
sources:
  - https://github.com/imunhatep/kube-node-ready
maintainers:
  - name: Artyom Sukharev
